version: '3.8'

services:
  focus-front-app:
    build:
      context: .
      args:
        - BASE_HREF="/servicios/datoteca/"
    ports:
      - "9100:80"
    environment:
#     - NODE_ENV=des, pre or pro
    networks: 
     - infraestructura_opendata

networks:
  infraestructura_opendata:
    name: infraestructura_opendata
    external: true