server {
    listen 80;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    location /servicios/datoteca/ {
        alias /usr/share/nginx/html/servicios/datoteca/;
        try_files $uri $uri/ /servicios/datoteca/index.html;

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }
}
